import "./styles/globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import DragScroll from "./components/DragScroll";

export const metadata = {
  title: "Renzo Viscio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <DragScroll />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
